name: smallx
channels:
  - conda-forge
  - pytorch
dependencies:
  # basics
  - ipython=7.13.0
  - python=3.8
  # numerical
  - arviz=0.8.3
  - matplotlib=3.1.3
  - numpy=1.18.1
  - pytorch=1.5
  - xarray=0.15.1
  # dev
  - black=19.10b0
  - isort=4.3.21
  - mypy=0.770
  - pytest=5.4.2
  - pytest-black=0.3.8
  - pytest-mypy=0.6.2
  # other
  - tqdm=4.46.1
